/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.ros.middleware.statepubsub.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class HybridDslUiModule extends AbstractHybridDslUiModule {

	public HybridDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
