/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.ros.middleware.statepubsub;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HybridDslRuntimeModule extends AbstractHybridDslRuntimeModule {
}
