/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.ros.middleware.statepubsub;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class HybridDslStandaloneSetup extends HybridDslStandaloneSetupGenerated {

	public static void doSetup() {
		new HybridDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
