/*
 * generated by Xtext 2.21.0
 */
package hu.sze.aut.ros.middleware.statepubsub.ide;


/**
 * Use this class to register ide components.
 */
public class RosNetworkDslIdeModule extends AbstractRosNetworkDslIdeModule {
}
