<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="statepubsubmodel" nsURI="http://jkk.sze.hu/statepubsubmodel"
    nsPrefix="statepubsubmodel">
  <eClassifiers xsi:type="ecore:EClass" name="Stack">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channels" upperBound="-1"
        eType="#//Channel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="networktype" ordered="false"
        upperBound="-1" eType="#//NetworkType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filepackage" upperBound="-1"
        eType="#//FilePackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sync_function_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="synchronizesState" eType="#//ContinousState"
        eOpposite="#//ContinousState/synchronizeWith"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPort" eSuperTypes="#//Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="channel" eType="#//Channel"
        eOpposite="#//Channel/portFrom"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="#//InternalNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="estimated_freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sync_time_stamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sample_tolerance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosRuntimeElement" abstract="true" eSuperTypes="#//DescriptiveElement #//AbstractRosFileElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousstate" upperBound="-1"
        eType="#//ContinousState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implements" eType="#//RosRuntimeElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="behavior" upperBound="-1"
        eType="#//Behavior" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="language" ordered="false"
        upperBound="-1" eType="#//LanguageType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeparameters" upperBound="-1"
        eType="#//AbstractNodeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" upperBound="-1" eType="#//Port"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filterconnection" upperBound="-1"
        eType="#//FilterConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internaledge" upperBound="-1"
        eType="#//InternalEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TopicMessage" eSuperTypes="#//AbstractMsgType"/>
  <eClassifiers xsi:type="ecore:EClass" name="Topic" eSuperTypes="#//Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TopicMessage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinousState" eSuperTypes="#//InternalNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="synchronizeWith" upperBound="-1"
        eType="#//InputPort" eOpposite="#//InputPort/synchronizesState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workerthread" eType="#//WorkerThread"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DescriptiveElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkerThread">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freq" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doFunc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Behavior" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="HybridSystem" eSuperTypes="#//Behavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" upperBound="-1"
        eType="#//Location" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" upperBound="-1"
        eType="#//ContinuousVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="event" upperBound="-1"
        eType="#//DiscreteEvent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invariant" upperBound="-1"
        eType="#//Invariant" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discreteevent" eType="#//DiscreteEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continuousvariable" eType="#//ContinuousVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContinuousVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousstate" eType="#//ContinousState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousvariable" eType="#//ContinuousVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiscreteEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FuzzyHybridSystem" eSuperTypes="#//HybridSystem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ruleset" upperBound="-1"
        eType="#//RuleSet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Invariant">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NetworkType">
    <eLiterals name="ROS1"/>
    <eLiterals name="ROS2" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LanguageType">
    <eLiterals name="Python"/>
    <eLiterals name="Cpp" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeParameter" eSuperTypes="#//AbstractNodeParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetvar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NodeParameterGroup" eSuperTypes="#//AbstractNodeParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeparameter" upperBound="-1"
        eType="#//NodeParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="config_obj" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generate_struct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNodeParameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DoubleParameter" eSuperTypes="#//NodeParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringParameter" eSuperTypes="#//NodeParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanParameter" eSuperTypes="#//NodeParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerParameter" eSuperTypes="#//NodeParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="step" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultval" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ErrorLocation" eSuperTypes="#//Location"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServiceType" eSuperTypes="#//AbstractMsgType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractMsgType" abstract="true" eSuperTypes="#//AbstractRosFileElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Channel" abstract="true" eSuperTypes="#//DescriptiveElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portFrom" eType="#//OutputPort"
        eOpposite="#//OutputPort/channel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Channel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//ServiceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilePackage" eSuperTypes="#//RosElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractroselement" upperBound="-1"
        eType="#//AbstractRosFileElement" containment="true" eOpposite="#//AbstractRosFileElement/filepackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filter" upperBound="-1"
        eType="#//FilterDefinition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractRosFileElement" abstract="true"
      eSuperTypes="#//RosElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="filepackage" eType="#//FilePackage"
        eOpposite="#//FilePackage/abstractroselement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RosElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="generateartifact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node" eSuperTypes="#//RosRuntimeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="LibraryNode" eSuperTypes="#//RosRuntimeElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FilterDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input_field" upperBound="-1"
        eType="#//SerializedField" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output_field" eType="#//SerializedField"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterConnection" eSuperTypes="#//InternalEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedfilter" eType="#//FilterDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//InternalNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" eType="#//InternalNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalNode" abstract="true" eSuperTypes="#//InternalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SerializedField">
    <eStructuralFeatures xsi:type="ecore:EReference" name="topicmessage" eType="#//TopicMessage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalEdge" abstract="true" eSuperTypes="#//InternalElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="InternalElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="debug" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectConnection" eSuperTypes="#//InternalEdge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="continousstate" eType="#//ContinousState"/>
  </eClassifiers>
</ecore:EPackage>
